config/routes.rb
Project::Application.routes.draw do
  
  resources :dashboards

  root :to => redirect('/dashboards')


  get '/login' , to: 'sessions#login'
  post '/login' , to: 'sessions#create'
  post '/logout' , to: 'sessions#destroy'
  get '/logout' , to: 'sessions#destroy'

  get '/schedule', :controller => 'employees', :action => 'show'
  
  resources :admin
end

app/views/admin/edit.html.erb
<h1> Edit Information </h1>

<%= form_tag admin_path , :method => :put do %>
	Username : <%= text_field("username", "username" , :value => @user.username ) %> <br>
	Password : <%= text_field("password", "password" , :value => "new password") %> <br>
	Name : <%= text_field("name", "name", :value => @user.name) %> <br>
	Surname : <%= text_field("surname", "surname",:value => @user.surname) %> <br>
	position : <%= select_tag 'position', options_for_select(["leader","employee"],@user.position)%> <br>

	<% if @user.position == "leader" %>
		<% department = @user.department1 %>
		<% list_department = [] %>
		<% department["["] = ""  %>
		<% department["]"] = "" %>
		<% department.gsub!('"',"") %>
		<% department %> 
	<% else %>
		<% department = @user.department1 %>
	<% end %>

	Department : <%= text_field("department1", "department1" , :value => department) %> <br>
	<%= submit_tag 'Submit' , :name => "submit" %> <br>
<% end %>

app/views/admin/index.html.erb
<h1> All Users </h1>

<div id="create-user-btn">
	<%= link_to "Create New User", new_admin_path %> <br>
</div>


<h2> All Leaders</h2>
<table>
	<thead>
		<tr>
			<th> ID </th>
			<th> Username </th>
			<th> ชื่อ-นามสกุล </th>
			<th> แผนกที่ควบคุม </th>
			<th> แก้ไขข้อมูล </th>
		</tr>
	</thead>
	<tbody>
		<% @leader_users.each do |leader| %>
		<tr>
			<td><%= leader.id %></td>
			<td><%= leader.username %></td>
			<td><%= leader.name + ' ' + leader.surname %></td>

			<% user = User.find(leader.id) %>
			<% department = user.department1 %>
			<% list_department = [] %>
			<% department["["] = ""  %>
			<% department["]"] = "" %>
			<% department.gsub!('"',"") %>
			<td> <%= department %> </td>
			<td> <%= link_to "Edit" , edit_admin_path(leader.id) %>
			<%=link_to "delete" , admin_path(leader.id), :method => :delete %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

<hr>


<h2> All Employees </h2>
<table>
	<thead>
		<tr>
			<th> ID </th>
			<th> Username </th>
			<th> ชื่อ-นามสกุล </th>
			<th> แผนก </th>
			<th> แก้ไขข้อมูล </th>
		</tr>
	</thead>
	<tbody>
		<% @worker_users.each do |worker| %>
		<tr>
			<td><%= worker.id %></td>
			<td><%= worker.username %></td>
			<td><%= worker.name + ' ' + worker.surname %></td>
			<td><%= worker.department1 %></td>
			<td> <%= link_to "Edit" , edit_admin_path(worker.id) %>
			<%=link_to "delete" , admin_path(worker.id), :method => :delete %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/new.html.erb
<h1> Create User </h1>

<%= form_tag new_admin_path , :method => :get do %>
	Username : <%= text_field("username", "username") %> <br>
	Password : <%= text_field("password", "password") %> <br>
	Name : <%= text_field("name", "name") %> <br>
	Surname : <%= text_field("surname", "surname") %> <br>
	position : <%= select_tag 'position', options_for_select(["leader","employee"])%> <br>
	Department : <%= text_field("department1", "department1") %> <br>
	<%= submit_tag 'Submit' , :name => "submit" %> <br>
<% end %>