config/routes.rb
Project::Application.routes.draw do
  
  resources :dashboards

  root :to => redirect('/dashboards')


  get '/login' , to: 'sessions#login'
  post '/login' , to: 'sessions#create'
  post '/logout' , to: 'sessions#destroy'
  get '/logout' , to: 'sessions#destroy'

  get '/schedule', :controller => 'employees', :action => 'show'
  
  resources :admin
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

	def index
		@leader = current_user
		@all_depart = check_department(@leader.id)
	end

	def time_plan(date)
		data = params.require(:emp).permit(:date, :OT)
		#day = params[:emp][:date]
		str_time_in = params[:time].split[0]
		str_time_out = params[:time].split[2]
		data[:date] = date.to_time
		data[:time_in] = (date+' '+str_time_in).to_time
		check_time_out = (date+' '+str_time_out).to_time
		tomorrow = ["00:00","00:30","01:00","01:30","02:00","02:30","03:00","03:30","04:00","04:30","05:00","05:30","06:00","06:30","07:00","07:30","08:00","08:30"]
		if tomorrow.include? str_time_out
			data[:time_out] = check_time_out + (3600*24)
		else
			data[:time_out] = check_time_out
		end
		if params[:emp][:OT] == ""
			data[:OT] = 0
		else
			data[:OT] = (params[:emp][:OT].to_f).ceil(1)	
		end
		return data
	end

	def edit
		@today = Time.current.strftime("%Y-%m-%d")
		@dep = params[:id]
		@users = User.where(:department1 => @dep)
		@employee = @users.select{|user| user.position=="employee"}
		emp_id_department = []
		@not_plan = []
		for em in @employee
			emp_id_department.append(em.id)
			if Plan.find_by(:date=>@today, :user_id=>em.id) == nil
				@not_plan.append(em)
			end
		end
		@emp_plan = Plan.where(:date => @today, :user_id => emp_id_department).order(params[:sort])

		# เช็คอัพเดตแพลน
		@time_now = (Time.current+3600).strftime('%H:%M')

		@table_date = @today

		@status = false
		if (params.key?('choose'))
			@status = true
			@date_in = params[:date_in].values[0]
			@table_date = @date_in
			emp_id_department = []
			@not_plan = []
			for em in @employee
				emp_id_department.append(em.id)
				if Plan.find_by(:date=>@date_in, :user_id=>em.id) == nil
					@not_plan.append(em)
				end
			end
			@emp_plan = Plan.where(:date => @date_in, :user_id => emp_id_department).order(params[:sort_choose])
		end

		# click to assign shift
		if (params.key?('ass_button'))

			@date_in = params[:date_in].values[0]
			@date_out = params[:date_out].values[0]
			
			@status = true
			if @date_in.to_time >= @today.to_time
				if @date_out.to_time >= @date_in.to_time
					# list of user id (tick checkbox)
					@uID_list = params[:select_user]

					time1 = @date_in.to_time
					time2 = @date_out.to_time

					dectime = (time2-time1) /(24*3600)
					

					for i in 0..dectime do 
						time_loop = ((@date_in.to_time) + (i*(24*3600)))
						date_loop = time_loop.strftime("%Y-%m-%d")
						new_time_out = (date_loop +' '+(params[:time].split[2])).to_time
						new_time_in = (date_loop +' '+(params[:time].split[0])).to_time
						tomorrow = ["00:00","00:30","01:00","01:30","02:00","02:30","03:00","03:30","04:00","04:30","05:00","05:30","06:00","06:30","07:00","07:30","08:00","08:30"]
						if tomorrow.include?(params[:time].split[2])
							new_time_out += (3600*24)
						end
						if @uID_list
							@uID_list.each do |uID|
								@all_user_plan = Plan.find_by(:user_id => uID , :date => date_loop) # get database
								@all_user_actual = Actual.find_by(:user_id => uID , :date => date_loop)
								if @all_user_plan != nil
									#กรณีเข้างาน-ออกงานแล้ว
									if @all_user_actual != nil && @all_user_actual.time_out != nil
										flash[:notice] = "Can't update shift"

									else
										# กรณีเข้างานแล้วแต่ยังไม่ได้ออกงานและเวลาแพลนเดิม สามารถอัพเดตโอทีได้
										if (@all_user_plan.time_in == new_time_in)&&(@all_user_plan.time_out == new_time_out )
											@all_user_plan.update(:OT => (params[:emp][:OT].to_f).ceil(1) )
											flash[:notice] = "Update OT success"
										else
											flash[:notice] = "Can't assign shift"
										end
									end

									# กรณีอัพเดตแพลนเมื่อเวลาปัจจุบันยังไม่ถึงแพลนที่จะกำหนดให้ (วันที่ปัจจุบัน)
									if (@all_user_actual == nil) && ( (new_time_in.strftime('%H:%M')).to_time >= @time_now.to_time )
										@all_user_plan.update(time_plan(date_loop))
										flash[:notice] = "Update Plan success"

									# กรณีอัพเดตแพลนเมื่อเวลาปัจจุบันยังไม่ถึงแพลนที่จะกำหนดให้ (ล่วงหน้า)
									elsif (@all_user_actual == nil) && ((new_time_in.strftime("%Y-%m-%d")).to_time > @today.to_time)
										@all_user_plan.update(time_plan(date_loop))
										flash[:notice] = "Update Plan success"
									end
										
									
								else
									#กรณีไม่มีแพลนสามารถสร้างแพลนได้
									@assign = Plan.create(time_plan(date_loop))
									user = User.find(uID.to_i)
									user.plans << @assign
									if @assign.save
										#if creation is successful, show up 'successful' message
										flash[:notice] = "Assign new shift successfully"
										#redirect_to edit_dashboard_path(@dep)
									else
										render 'edit'
									end
								end
							end
							
						end
					
					end
				else
					flash[:notice] = "Date should be sort"
					redirect_to edit_dashboard_path(@dep)
				end
			else
				flash[:notice] = "You cannot assign plan in the pass!"
			end
		end

		# time
		@all_time = ["00:00 - 09:00","00:30 - 09:30","01:00 - 10:00","01:30 - 10:30","02:00 - 11:00","02:30 - 11:30",
					"03:00 - 12:00","03:30 - 12:30","04:00 - 13:00","04:30 - 13:30","05:00 - 14:00","05:30 - 14:30",
					"06:00 - 15:00","06:30 - 15:30","07:00 - 16:00","07:30 - 16:30","08:00 - 17:00","08:30 - 17:30",
					"09:00 - 18:00","09:30 - 18:30","10:00 - 19:00","10:30 - 19:30","11:00 - 20:00","11:30 - 20:30",
					"12:00 - 21:00","12:30 - 21:30","13:00 - 22:00","13:30 - 22:30","14:00 - 23:00","14:30 - 23:30",
					"15:00 - 00:00","15:30 - 00:30","16:00 - 01:00","16:30 - 01:30","17:00 - 02:00","17:30 - 02:30",
					"18:00 - 03:00","18:30 - 03:30","19:00 - 04:00","19:30 - 04:30","20:00 - 05:00","20:30 - 05:30",
					"21:00 - 06:00","21:30 - 06:30","22:00 - 07:00","22:30 - 07:30","23:00 - 08:00","23:30 - 08:30"]

		@default_select = "00:00 - 09:00"

		

		if (params.key?("delete"))
			list_userid = params[:select_user]

			date_in = params[:date_in].values[0]
			date_out = params[:date_out].values[0]

			time1 = date_in.to_time
			time2 = date_out.to_time

			dectime = (time2-time1) /(24*3600)

			for i in 0..dectime do
				day_loop = ((date_in.to_time) + (i*(24*3600)))

				if list_userid != nil 
					list_userid.each do |user|
						actual = Actual.find_by(:user_id => user , :date => day_loop)
						plan = Plan.find_by(:date => day_loop , :user_id => user)
						if plan != nil && actual == nil
							plan.destroy
							flash[:notice] = "Delete plan success"
						else
							flash[:notice] = "Warning! Please check you plan & actual"
						end
					end
				end
			end

		end
	end


	def show
		@department_name = params[:id]
		@all_workers = User.where(:position => 'employee', :department1 => @department_name)
	
		@all_time = ["all","00:00 - 09:00","00:30 - 09:30","01:00 - 10:00","01:30 - 10:30","02:00 - 11:00","02:30 - 11:30",
					"03:00 - 12:00","03:30 - 12:30","04:00 - 13:00","04:30 - 13:30","05:00 - 14:00","05:30 - 14:30",
					"06:00 - 15:00","06:30 - 15:30","07:00 - 16:00","07:30 - 16:30","08:00 - 17:00","08:30 - 17:30",
					"09:00 - 18:00","09:30 - 18:30","10:00 - 19:00","10:30 - 19:30","11:00 - 20:00","11:30 - 20:30",
					"12:00 - 21:00","12:30 - 21:30","13:00 - 22:00","13:30 - 22:30","14:00 - 23:00","14:30 - 23:30",
					"15:00 - 00:00","15:30 - 00:30","16:00 - 01:00","16:30 - 01:30","17:00 - 02:00","17:30 - 02:30",
					"18:00 - 03:00","18:30 - 03:30","19:00 - 04:00","19:30 - 04:30","20:00 - 05:00","20:30 - 05:30",
					"21:00 - 06:00","21:30 - 06:30","22:00 - 07:00","22:30 - 07:30","23:00 - 08:00","23:30 - 08:30"]

		@select = "all" 

		@status = false

		if (params.key?("choose"))
			@select = params[:time_in]
			@calender = params[:date_work].values[0]
			@t_in = (@calender + ' '+ @select[0..4]).to_time
			@status = true
		end

	end

	def check_department(leader_id)
		user = User.find(leader_id)
		department = user.department1
		list_department = []
		department["["] = "" 
		department["]"] = ""
		n_string = department.split(",")

		n_string.each do |all|
			all.gsub!(" ","")
    		all.gsub!('"',"")
    		list_department.append(all)
    
    	end
		return list_department
	end

end

app/views/dashboards/_dashboard_form.html.erb
<% @all_depart.each do |department|%>
    <% minus_ot = 0 %>
    
    <% num_now = 0 %>
    <% num_plan = 0 %>
    <% day = Time.current.strftime("%Y-%m-%d") %>
    <% all_worker = User.where(:department1 => department , :position => "employee") %>

    <% all_worker.each do |worker| %>

        <%# จำนวนคนเข้างาน เทียบกับ แพลนที่ให้ทั้งวัน %>
        <% all_plan = worker.plans.find_by_date(day) %>
            <% if all_plan != nil %>
                <% num_plan += 1 %>
            <% end %>

        <% all_actual = worker.actuals.find_by_date(day) %>
            <% if all_actual != nil && all_actual.time_in != nil && all_actual.time_out == nil %>
                <% num_now += 1 %>
            <% end %>


            <%# เช็คโอทีติดลบ %>
            <% if (all_actual != nil) && (all_actual.OT != nil) %>
                <% if all_actual.OT < 0  %>
                    <% minus_ot += 1 %>
                <% end %>
            <% end %>


    <% end %>

    <% if num_now != 0 && num_plan !=0 %>
        <% percent = (num_now * 100 / num_plan) %> 
    <% else %>
        <% percent = 0 %> 
    <% end %>



    <div class="item-container">
        <div class="title-department">
            <%= link_to department ,  dashboard_path(department), :class => "title-department-tag"  %>
            <% if minus_ot > 0 %>
                <div class="title-department-tag" id="ot"><%= "!"%></div>
            <% end %>
        </div>
        <div class="percent-container">
        <p> <%=  num_now.to_s + ' / ' + num_plan.to_s %> </p>
        <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: <%= percent%>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        </div>
        <div class="actual-btn">
            <%= link_to ('<i class="fa fa-clock-o" aria-hidden="true" style="font-size:1.5em"></i>').html_safe,  dashboard_path(department)  %>
           
        </div>
        <div class="plan-btn">
            <%= link_to ('<i class="fa fa-pencil" aria-hidden="true" style="font-size:1.5em"></i>').html_safe,  edit_dashboard_path(department)  %>
        </div>
    </div>

<% end %>

app/views/dashboards/edit.html.erb
<body>
  <h1 class='title'>Plan แผนก <%= @dep %></h2>

    <%= form_tag(edit_dashboard_path(@dep), method: 'get') do %>
      <div class="pick-time">


      <div class="section-select-container">
        Date assign

        <% if @status == true %>
          <%= date_field("date_in","date_in" , :value => @date_in) %>
        <% else %>
          <%= date_field("date_in","date_in" , :value => @today) %>
        <% end %>
        <%= submit_tag 'select' , :name => "choose", :id =>"submit-btn", :style => "display:none" %>
        to
        <%= date_field("date_out","date_out", :value => @today,:min => @today) %>

      </div>
      <div class="controll-container">


      <div class="time-plan-container">

        Time <%= select_tag :time, options_for_select(@all_time, @default_select)  %>
        OT <%= text_field :emp, :OT %>
        <%= submit_tag "Submit" , :name=>'ass_button' , :class => "summit-plan"%>

      </div>
      <div class="delete-section">
        <%= submit_tag "Delete" , :name=>'delete' %>
      </div>
      </div>

      </div>


  <div class="table-container">
    <h4>แผนงานวันที่ : <%= @table_date %></h4>
    <table>
      <tr>
        <th><%= check_box_tag :check_all %></th>
        <th>ชื่อ-นามสกุล</th>
        <% if @emp_plan != nil %>
          <th><%= link_to "เวลาเข้างาน", :sort=>"time_in" %></th>
        <% else %>
          <th><%= link_to "เวลาเข้างาน", :sort_select=>"time_in" %></th>
        <% end %>
        <th>เวลาออกงาน</th>
        <th>OT Plane</th>
      </tr>
      <% if @emp_plan != nil %>
      <% @emp_plan.each do |plan| %>
      <tr>
        <td><%= check_box_tag "select_user[]", plan.user_id %></td>
        <td><%= User.find(plan.user_id).name.to_s+" "+User.find(plan.user_id).surname.to_s %></td>
        <td><%= plan.time_in.strftime('%H:%M') %></td>
        <td><%= plan.time_out.strftime('%H:%M') %></td>
        <td><%= plan.OT.to_s %></td>
      </tr>
      <% end %>
      <% end %>
      <% if @not_plan != nil %>
      <% @not_plan.each do |not_plan_emp| %>
      <tr>
        <td><%= check_box_tag "select_user[]", not_plan_emp.id %></td>
        <td><%= not_plan_emp.name.to_s+" "+not_plan_emp.surname.to_s %></td>
        <td> - </td>
        <td> - </td>
        <td> - </td>
      </tr>
      <% end %>
      <% end %>
    </table>
  <% end %>
</div>

</body>

<%= javascript_pack_tag 'select_all', 'data-turbolinks-track':'reload' %>
<%= javascript_pack_tag 'edit', 'data-turbolinks-track':'reload' %>

app/views/dashboards/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    
  </head>
  

  <body>
    <h1>Dash Board </h1>
    <h2>จัดการแผนก</h2>
    <div class="dashboard-cotainer">
      <%= render :partial=>'dashboard_form' %>  
    </div>
  </body>
</html>

app/views/dashboards/show.html.erb
<h1 class="title">
	<%= "แผนก : " + @department_name %>
</h1>

<div class="pick_time">
	<div class="item">
		<%= link_to 'Plan', edit_dashboard_path(@department_name), :class =>"plan-btn-show" %><br>
	</div>
	<% day = Time.current.strftime("%Y-%m-%d") %>
	<% date = day.to_time %>
	<div class="item">
		<%= form_tag dashboard_path(@department_name) , :method => :get do %>
		<div class="form-container">
			<div class="item-form">
				<a>กะการทำงาน :</a>
				<%= select_tag 'time_in', options_for_select(@all_time, @select)  %>
			</div>
			<div class="item-form">
				วันที่ทำงาน :
				<% if @status == true %>
					<%= date_field("date_work", "date_work" , :value => @calender) %>
				<% else %>
					<%= date_field("date_work", "date_work" , :value => day) %>
				<% end %>
			</div>
			<div class="item-form">
				<%= submit_tag 'select' , :name => "choose" , :class=>"select-time-btn", style:"display:none;" %>
			</div>
		</div>
		<% end %>
	</div>

<% num_now = 0 %>
<% num_plan = 0 %>

<% @all_workers.each do |num| %>
	<% if @status == true %>
		<% actual = num.actuals.find_by_date(@calender) %>
	<% else %>
		<% actual = num.actuals.find_by_date(day) %>
	<% end %>
	<% if actual != nil %>
		<% if @select == "all"  %>
			<% if actual.time_in != nil && actual.time_out == nil %>
				<% num_now += 1 %>
			<% end %>
		<% else %>
			<% plan = num.plans.find_by(:date => @calender , :time_in => @t_in) %>
			<% if actual.time_in != nil && actual.time_out == nil && plan != nil %>
				<% num_now += 1 %>
			<% end %>

		<% end %>
	<% end %>



	<% if @select == "all"  %>
		<% if @status == false %>
			<% plan = num.plans.find_by_date(date) %>
		<% elsif @status == true %>
			<% plan = num.plans.find_by_date(@calender) %>
		<% end %>

		<% if plan != nil %>
			<% num_plan += 1 %>
		<% end %>

	<% else %>
		<% plan = num.plans.find_by(:date => @calender , :time_in => @t_in) %>
		<% if plan != nil %>
			<% num_plan += 1 %>
		<% end %>

	<% end %>


<% end %>
<div class="item">
	<%= "จำนวนคน : "+ num_now.to_s + " / " + num_plan.to_s %>
</div>
</div>

<div class="table-container">
<table >
	<thead>
		<tr>
			<th> ชื่อ-นามสกุล </th>
			<th> เวลาเข้างาน </th>
			<th> เวลาออกงาน </th>
			<th> OT </th>
		</tr>
	</thead>
	<tbody>
		<% @all_workers.each do |worker| %>
			<tr>

				<% if @status == false %>
					<% worker_all_actuals = worker.actuals.find_by_date(date) %>
				<% elsif @status == true %>
					<% worker_all_actuals = worker.actuals.find_by_date(@calender) %>
				<% end %>

				<% if @select == "all"  %>
					<% if @status == false %>
						<% worker_all_plan = worker.plans.find_by_date(date) %>
					<% elsif @status == true %>
						<% worker_all_plan = worker.plans.find_by_date(@calender) %>
					<% end %>

				<% else %>
					<% worker_all_plan = worker.plans.find_by(:date => @calender , :time_in => @t_in) %>
				<% end %>

				<% if worker_all_actuals != nil && worker_all_plan != nil  %>

					<td><%= worker.name + " " + worker.surname %></td>


					<%# time in %>
					<% if worker_all_actuals.time_in != nil  %>

						<% if (worker_all_actuals.time_in.strftime('%H:%M').to_time) <= ((worker_all_plan.time_in + (3600*12) + 300).strftime('%H:%M').to_time)%>
							
							<td><%= "hello" +  worker_all_actuals.time_in.strftime('%H:%M') + '/' + (worker_all_plan.time_in + (3600*12)).strftime('%H:%M') %></td>
						<% else %>
							<td><%= "late" +  worker_all_actuals.time_in.strftime('%H:%M') + '/' + (worker_all_plan.time_in + (3600*12)).strftime('%H:%M') %></td>
						<% end %>
					<% else %>
						<td> <%= '- / ' + (worker_all_plan.time_in + (3600*12)).strftime('%H:%M') %> </td>
					<% end %>


					<%# time out %>
					<% if worker_all_actuals.time_out != nil %>

						<% if (worker_all_actuals.time_out.strftime('%H:%M').to_time) <= ((worker_all_plan.time_out + (3600*12) + 300).strftime('%H:%M').to_time)%>
							
							<td><%= "late" +  worker_all_actuals.time_out.strftime('%H:%M') + '/' + (worker_all_plan.time_out+(3600*12)).strftime('%H:%M') %></td>
						<% else %>
							<td><%= "hello" +  worker_all_actuals.time_out.strftime('%H:%M') + '/' + (worker_all_plan.time_out + (3600*12)).strftime('%H:%M') %></td>
						<% end %>
					<% else %>
						<td> <%= '- / ' + (worker_all_plan.time_out+(3600*12)).strftime('%H:%M') %></td>
					<% end %>


					<%# ot %>
					<% if worker_all_actuals.OT != nil %>
						
						<% if worker_all_actuals.OT < 0 %>
							
							<td><%= "late" + worker_all_actuals.OT.to_s + '/' + worker_all_plan.OT.to_s %></td>
						<% else %>
							<td><%= "hello" +  worker_all_actuals.OT.to_s + '/' + worker_all_plan.OT.to_s %></td>
						<% end %>

					<% else %>
						<td> <%= '- / ' + worker_all_plan.OT.to_s %></td>
					<% end %>


				<% else %>
					<% if worker_all_plan != nil %>
						<td><%= worker.name + " " + worker.surname %></td>
						<td> <%= '- / ' + (worker_all_plan.time_in + (3600*12)).strftime('%H:%M') %></td>
						<td> <%= '- / ' + (worker_all_plan.time_out+(3600*12)).strftime('%H:%M') %></td>
						<td> <%= '- / ' + worker_all_plan.OT.to_s %></td>

					<% end %>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>
</div>

<script type="text/javascript">
      setTimeout("location.reload();",600000);
</script>
<%= javascript_pack_tag 'show', 'data-turbolinks-track': 'reload' %>